name: geppo
version: '0.2.0.0'
category: Text
author: TANIGUCHI Kohei <a.d.xvii.kal.mai@gmail.com>
maintainer: TANIGUCHI Kohei <a.d.xvii.kal.mai@gmail.com>
copyright: 2017 TANIGUCHI Kohei
license: BSD3
github: cohei/geppo
extra-source-files:
  - README.md

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wmissing-import-lists
  - -Wmissing-local-signatures
  - -Wmonomorphism-restriction
  - -Wpartial-fields
  - -Wredundant-constraints
  - -fdefer-typed-holes

library:
  source-dirs: src
  dependencies:
    - aeson
    - base >=4.7 && <5
    - bytestring
    - data-default
    - lens
    - lens-aeson
    - pandoc
    - pandoc-types
    - req
    - text
    - time
executables:
  geppo:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base
      - geppo
      - text
